// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: protos/opsportal_deploy_sandbox.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DeploySandboxRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SubscriptionName string                 `protobuf:"bytes,1,opt,name=subscription_name,json=subscriptionName,proto3" json:"subscription_name,omitempty"`
	ServiceDetails   []*ServiceDetails      `protobuf:"bytes,2,rep,name=service_details,json=serviceDetails,proto3" json:"service_details,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeploySandboxRequest) Reset() {
	*x = DeploySandboxRequest{}
	mi := &file_protos_opsportal_deploy_sandbox_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploySandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploySandboxRequest) ProtoMessage() {}

func (x *DeploySandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_opsportal_deploy_sandbox_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploySandboxRequest.ProtoReflect.Descriptor instead.
func (*DeploySandboxRequest) Descriptor() ([]byte, []int) {
	return file_protos_opsportal_deploy_sandbox_proto_rawDescGZIP(), []int{0}
}

func (x *DeploySandboxRequest) GetSubscriptionName() string {
	if x != nil {
		return x.SubscriptionName
	}
	return ""
}

func (x *DeploySandboxRequest) GetServiceDetails() []*ServiceDetails {
	if x != nil {
		return x.ServiceDetails
	}
	return nil
}

type ServiceDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceDetails) Reset() {
	*x = ServiceDetails{}
	mi := &file_protos_opsportal_deploy_sandbox_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceDetails) ProtoMessage() {}

func (x *ServiceDetails) ProtoReflect() protoreflect.Message {
	mi := &file_protos_opsportal_deploy_sandbox_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceDetails.ProtoReflect.Descriptor instead.
func (*ServiceDetails) Descriptor() ([]byte, []int) {
	return file_protos_opsportal_deploy_sandbox_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceDetails) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceDetails) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type DeploySandboxResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeploySandboxResponse) Reset() {
	*x = DeploySandboxResponse{}
	mi := &file_protos_opsportal_deploy_sandbox_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeploySandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeploySandboxResponse) ProtoMessage() {}

func (x *DeploySandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_opsportal_deploy_sandbox_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeploySandboxResponse.ProtoReflect.Descriptor instead.
func (*DeploySandboxResponse) Descriptor() ([]byte, []int) {
	return file_protos_opsportal_deploy_sandbox_proto_rawDescGZIP(), []int{2}
}

var File_protos_opsportal_deploy_sandbox_proto protoreflect.FileDescriptor

const file_protos_opsportal_deploy_sandbox_proto_rawDesc = "" +
	"\n" +
	"%protos/opsportal_deploy_sandbox.proto\x12\x1aopsportal.deploysandbox.v1\"\x98\x01\n" +
	"\x14DeploySandboxRequest\x12+\n" +
	"\x11subscription_name\x18\x01 \x01(\tR\x10subscriptionName\x12S\n" +
	"\x0fservice_details\x18\x02 \x03(\v2*.opsportal.deploysandbox.v1.ServiceDetailsR\x0eserviceDetails\"I\n" +
	"\x0eServiceDetails\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\"\x17\n" +
	"\x15DeploySandboxResponse2\x85\x01\n" +
	"\rDeploySandbox\x12t\n" +
	"\rDeploySandbox\x120.opsportal.deploysandbox.v1.DeploySandboxRequest\x1a1.opsportal.deploysandbox.v1.DeploySandboxResponseB\x10Z\x0e/protos;protosb\x06proto3"

var (
	file_protos_opsportal_deploy_sandbox_proto_rawDescOnce sync.Once
	file_protos_opsportal_deploy_sandbox_proto_rawDescData []byte
)

func file_protos_opsportal_deploy_sandbox_proto_rawDescGZIP() []byte {
	file_protos_opsportal_deploy_sandbox_proto_rawDescOnce.Do(func() {
		file_protos_opsportal_deploy_sandbox_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_opsportal_deploy_sandbox_proto_rawDesc), len(file_protos_opsportal_deploy_sandbox_proto_rawDesc)))
	})
	return file_protos_opsportal_deploy_sandbox_proto_rawDescData
}

var file_protos_opsportal_deploy_sandbox_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_opsportal_deploy_sandbox_proto_goTypes = []any{
	(*DeploySandboxRequest)(nil),  // 0: opsportal.deploysandbox.v1.DeploySandboxRequest
	(*ServiceDetails)(nil),        // 1: opsportal.deploysandbox.v1.ServiceDetails
	(*DeploySandboxResponse)(nil), // 2: opsportal.deploysandbox.v1.DeploySandboxResponse
}
var file_protos_opsportal_deploy_sandbox_proto_depIdxs = []int32{
	1, // 0: opsportal.deploysandbox.v1.DeploySandboxRequest.service_details:type_name -> opsportal.deploysandbox.v1.ServiceDetails
	0, // 1: opsportal.deploysandbox.v1.DeploySandbox.DeploySandbox:input_type -> opsportal.deploysandbox.v1.DeploySandboxRequest
	2, // 2: opsportal.deploysandbox.v1.DeploySandbox.DeploySandbox:output_type -> opsportal.deploysandbox.v1.DeploySandboxResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_opsportal_deploy_sandbox_proto_init() }
func file_protos_opsportal_deploy_sandbox_proto_init() {
	if File_protos_opsportal_deploy_sandbox_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_opsportal_deploy_sandbox_proto_rawDesc), len(file_protos_opsportal_deploy_sandbox_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_opsportal_deploy_sandbox_proto_goTypes,
		DependencyIndexes: file_protos_opsportal_deploy_sandbox_proto_depIdxs,
		MessageInfos:      file_protos_opsportal_deploy_sandbox_proto_msgTypes,
	}.Build()
	File_protos_opsportal_deploy_sandbox_proto = out.File
	file_protos_opsportal_deploy_sandbox_proto_goTypes = nil
	file_protos_opsportal_deploy_sandbox_proto_depIdxs = nil
}
