// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.0
// source: protos/opsportal_deploy_sandbox.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeploySandbox_DeploySandbox_FullMethodName = "/opsportal.deploysandbox.v1.DeploySandbox/DeploySandbox"
)

// DeploySandboxClient is the client API for DeploySandbox service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeploySandboxClient interface {
	DeploySandbox(ctx context.Context, in *DeploySandboxRequest, opts ...grpc.CallOption) (*DeploySandboxResponse, error)
}

type deploySandboxClient struct {
	cc grpc.ClientConnInterface
}

func NewDeploySandboxClient(cc grpc.ClientConnInterface) DeploySandboxClient {
	return &deploySandboxClient{cc}
}

func (c *deploySandboxClient) DeploySandbox(ctx context.Context, in *DeploySandboxRequest, opts ...grpc.CallOption) (*DeploySandboxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeploySandboxResponse)
	err := c.cc.Invoke(ctx, DeploySandbox_DeploySandbox_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeploySandboxServer is the server API for DeploySandbox service.
// All implementations must embed UnimplementedDeploySandboxServer
// for forward compatibility.
type DeploySandboxServer interface {
	DeploySandbox(context.Context, *DeploySandboxRequest) (*DeploySandboxResponse, error)
	mustEmbedUnimplementedDeploySandboxServer()
}

// UnimplementedDeploySandboxServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeploySandboxServer struct{}

func (UnimplementedDeploySandboxServer) DeploySandbox(context.Context, *DeploySandboxRequest) (*DeploySandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeploySandbox not implemented")
}
func (UnimplementedDeploySandboxServer) mustEmbedUnimplementedDeploySandboxServer() {}
func (UnimplementedDeploySandboxServer) testEmbeddedByValue()                       {}

// UnsafeDeploySandboxServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeploySandboxServer will
// result in compilation errors.
type UnsafeDeploySandboxServer interface {
	mustEmbedUnimplementedDeploySandboxServer()
}

func RegisterDeploySandboxServer(s grpc.ServiceRegistrar, srv DeploySandboxServer) {
	// If the following call pancis, it indicates UnimplementedDeploySandboxServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeploySandbox_ServiceDesc, srv)
}

func _DeploySandbox_DeploySandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeploySandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeploySandboxServer).DeploySandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeploySandbox_DeploySandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeploySandboxServer).DeploySandbox(ctx, req.(*DeploySandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeploySandbox_ServiceDesc is the grpc.ServiceDesc for DeploySandbox service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeploySandbox_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opsportal.deploysandbox.v1.DeploySandbox",
	HandlerType: (*DeploySandboxServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DeploySandbox",
			Handler:    _DeploySandbox_DeploySandbox_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/opsportal_deploy_sandbox.proto",
}
